
#set_property PACKAGE_PIN F19 [get_ports sys_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

#set_property PACKAGE_PIN M20 [get_ports sys_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

#set_property PACKAGE_PIN L17 [get_ports pix_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports pix_clk]

#set_property PACKAGE_PIN F19 [get_ports h_sync]
#set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
#set_property PACKAGE_PIN K17 [get_ports v_sync]
#set_property IOSTANDARD LVCMOS33 [get_ports v_sync]

#set_property PACKAGE_PIN F20 [get_ports rgb_r0]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_r0]
#set_property PACKAGE_PIN E19 [get_ports rgb_r1]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_r1]
#set_property PACKAGE_PIN H18 [get_ports rgb_r2]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_r2]
#set_property PACKAGE_PIN D19 [get_ports rgb_r3]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_r3]

#set_property PACKAGE_PIN D20 [get_ports rgb_g0]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_g0]
#set_property PACKAGE_PIN D18 [get_ports rgb_g1]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_g1]
#set_property PACKAGE_PIN H17 [get_ports rgb_g2]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_g2]
#set_property PACKAGE_PIN C20 [get_ports rgb_g3]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_g3]

#set_property PACKAGE_PIN B19 [get_ports rgb_b0]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_b0]
#set_property PACKAGE_PIN B20 [get_ports rgb_b1]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_b1]
#set_property PACKAGE_PIN A20 [get_ports rgb_b2]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_b2]
#set_property PACKAGE_PIN H16 [get_ports rgb_b3]
#set_property IOSTANDARD LVCMOS33 [get_ports rgb_b3]

set_property PACKAGE_PIN U19 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property PACKAGE_PIN V20 [get_ports v_sync]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]

set_property PACKAGE_PIN U20 [get_ports rgb_r0]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r0]
set_property PACKAGE_PIN T19 [get_ports rgb_r1]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r1]
set_property PACKAGE_PIN P19 [get_ports rgb_r2]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r2]
set_property PACKAGE_PIN T20 [get_ports rgb_r3]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r3]

set_property PACKAGE_PIN R18 [get_ports rgb_g0]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g0]
set_property PACKAGE_PIN R19 [get_ports rgb_g1]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g1]
set_property PACKAGE_PIN P20 [get_ports rgb_g2]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g2]
set_property PACKAGE_PIN N17 [get_ports rgb_g3]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g3]

set_property PACKAGE_PIN P18 [get_ports rgb_b0]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_b0]
set_property PACKAGE_PIN M17 [get_ports rgb_b1]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_b1]
set_property PACKAGE_PIN M19 [get_ports rgb_b2]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_b2]
set_property PACKAGE_PIN N20 [get_ports rgb_b3]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_b3]